=== glygener/glygen-backend-api/specs/site/detail/response.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "start_pos": {
            "type": "integer"
        },
        "end_pos": {
            "type": "integer"
        },
        "up_seq": {
            "type": "string"
        },
        "site_seq": {
            "type": "string"
        },
        "down_seq": {
            "type": "string"
        },
        "uniprot_canonical_ac": {
            "type": "string"
        },
        "species": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "taxid": {
                        "type": "integer"
                    },
                    "evidence": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "database": {
                                    "type": "string"
                                },
                                "id": {
                                    "type": "string"
                                },
                                "url": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "database",
                                "id",
                                "url"
                            ]
                        }
                    },
                    "common_name": {
                        "type": "string"
                    }
                },
                "required": [
                    "common_name",
                    "evidence",
                    "name",
                    "taxid"
                ]
            }
        },
        "glycosylation": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "glytoucan_ac": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "subtype": {
                        "type": "string"
                    },
                    "site_category": {
                        "type": "string"
                    },
                    "site_seq": {
                        "type": "string"
                    },
                    "relation": {
                        "type": "string"
                    },
                    "comment": {
                        "type": "string"
                    },
                    "start_aa": {
                        "type": "string"
                    },
                    "end_aa": {
                        "type": "string"
                    },
                    "residue": {
                        "type": "string"
                    },
                    "evidence": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "database": {
                                    "type": "string"
                                },
                                "url": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "database",
                                "id",
                                "url"
                            ]
                        }
                    }
                },
                "required": [
                    "comment",
                    "end_aa",
                    "evidence",
                    "glytoucan_ac",
                    "relation",
                    "residue",
                    "site_category",
                    "site_seq",
                    "start_aa",
                    "subtype",
                    "type"
                ]
            }
        },
        "snv": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "evidence": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "database": {
                                    "type": "string"
                                },
                                "url": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "database",
                                "id",
                                "url"
                            ]
                        }
                    },
                    "glycoeffect": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "sequence_org": {
                        "type": "string"
                    },
                    "sequence_mut": {
                        "type": "string"
                    },
                    "comment": {
                        "type": "string"
                    },
                    "chr_id": {
                        "type": "string"
                    },
                    "chr_pos": {
                        "type": "string"
                    },
                    "ref_nt": {
                        "type": "string"
                    },
                    "alt_nt": {
                        "type": "string"
                    },
                    "minor_allelic_frequency": {
                        "type": "string"
                    },
                    "keywords": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": [
                    "alt_nt",
                    "chr_id",
                    "chr_pos",
                    "comment",
                    "evidence",
                    "glycoeffect",
                    "keywords",
                    "minor_allelic_frequency",
                    "ref_nt",
                    "sequence_mut",
                    "sequence_org"
                ]
            }
        },
        "all_sites": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string"
                    },
                    "site_list": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "start_pos": {
                                    "type": "string"
                                },
                                "end_pos": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "end_pos",
                                "start_pos"
                            ]
                        }
                    }
                },
                "required": [
                    "site_list",
                    "type"
                ]
            }
        },
        "categories": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "mutagenesis": {
            "type": "array"
        },
        "phosphorylation": {
            "type": "array"
        },
        "glycation": {
            "type": "array"
        },
        "neighbors": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "distance": {
                        "type": "integer"
                    },
                    "direction": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "categories": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": [
                    "categories",
                    "direction",
                    "distance",
                    "id"
                ]
            }
        },
        "uniprot_id": {
            "type": "string"
        },
        "uniprot": {
            "type": "object",
            "properties": {
                "uniprot_canonical_ac": {
                    "type": "string"
                },
                "uniprot_id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "length": {
                    "type": "integer"
                }
            },
            "required": [
                "length",
                "uniprot_canonical_ac",
                "uniprot_id",
                "url"
            ]
        },
        "sequence": {
            "type": "object",
            "properties": {
                "sequence": {
                    "type": "string"
                },
                "length": {
                    "type": "integer"
                },
                "header": {
                    "type": "string"
                }
            },
            "required": [
                "header",
                "length",
                "sequence"
            ]
        },
        "mass": {
            "type": "object",
            "properties": {
                "chemical_mass": {
                    "type": "number"
                },
                "monoisotopic_mass": {
                    "type": "number"
                }
            },
            "required": [
                "chemical_mass",
                "monoisotopic_mass"
            ]
        },
        "protein_names": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "resource": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "name",
                    "resource",
                    "type",
                    "url"
                ]
            }
        },
        "gene": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    },
                    "locus": {
                        "type": "object",
                        "properties": {
                            "chromosome": {
                                "type": "string"
                            },
                            "start_pos": {
                                "type": "integer"
                            },
                            "end_pos": {
                                "type": "integer"
                            },
                            "strand": {
                                "type": "string"
                            },
                            "evidence": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "database": {
                                            "type": "string"
                                        },
                                        "id": {
                                            "type": "string"
                                        },
                                        "url": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "database",
                                        "id",
                                        "url"
                                    ]
                                }
                            }
                        },
                        "required": [
                            "chromosome",
                            "end_pos",
                            "evidence",
                            "start_pos",
                            "strand"
                        ]
                    }
                },
                "required": [
                    "locus",
                    "name",
                    "url"
                ]
            }
        },
        "gene_names": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "resource": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "name",
                    "resource",
                    "type",
                    "url"
                ]
            }
        },
        "refseq": {
            "type": "object",
            "properties": {
                "ac": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "ac",
                "name",
                "summary",
                "url"
            ]
        }
    },
    "required": [
        "all_sites",
        "categories",
        "down_seq",
        "end_pos",
        "gene",
        "gene_names",
        "glycation",
        "glycosylation",
        "id",
        "mass",
        "mutagenesis",
        "neighbors",
        "phosphorylation",
        "protein_names",
        "refseq",
        "sequence",
        "site_seq",
        "snv",
        "species",
        "start_pos",
        "uniprot",
        "uniprot_canonical_ac",
        "uniprot_id",
        "up_seq"
    ]
}

=== glygener/glygen-backend-api/tests/responses/site_detail.json
{
    "id": "P02724-1.52.52",
    "start_pos": 52,
    "end_pos": 52,
    "up_seq": "SSSVTKSYISSQTNDTHKRD",
    "site_seq": "T",
    "down_seq": "YAATPRAHEVSEISVRTVYP",
    "uniprot_canonical_ac": "P02724-1",
    "species": [
        {
            "name": "Homo sapiens",
            "taxid": 9606,
            "evidence": [
                {
                    "database": "UniProtKB",
                    "id": "P02724",
                    "url": "https://www.uniprot.org/uniprot/P02724"
                }
            ],
            "common_name": "Human"
        }
    ],
    "glycosylation": [
        {
            "glytoucan_ac": "G00031MO",
            "type": "O-linked",
            "subtype": "",
            "site_category": "reported_with_glycan",
            "site_seq": "T",
            "relation": "attached",
            "comment": "GlycoSuiteDB  curation notes. Reported structure can be attached to the following: S-21, T-22, T-23, T-29, S-30, T-31, S-32, T-36, S-38, S-41, T-44, N-45, T-52, T-56, S-63, S-66, T-69",
            "start_aa": "Thr",
            "end_aa": "Thr",
            "residue": "Thr",
            "evidence": [
                {
                    "id": "P02724",
                    "database": "UniCarbKB",
                    "url": "http://unicarbkb.org/proteinsummary/P02724/annotated"
                },
                {
                    "id": "6190803",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/6190803"
                },
                {
                    "id": "4091823",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/4091823"
                },
                {
                    "id": "3514617",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/3514617"
                },
                {
                    "id": "6619126",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/6619126"
                },
                {
                    "id": "7430095",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/7430095"
                },
                {
                    "id": "8384526",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/8384526"
                }
            ]
        },
        {
            "glytoucan_ac": "G01614ZM",
            "type": "O-linked",
            "subtype": "",
            "site_category": "reported_with_glycan",
            "site_seq": "T",
            "relation": "attached",
            "comment": "GlycoSuiteDB  curation notes. Reported structure can be attached to the following: S-21, T-22, T-23, T-29, S-30, T-31, S-32, T-36, S-38, S-41, T-44, N-45, T-52, T-56, S-63, S-66, T-69",
            "start_aa": "Thr",
            "end_aa": "Thr",
            "residue": "Thr",
            "evidence": [
                {
                    "id": "P02724",
                    "database": "UniCarbKB",
                    "url": "http://unicarbkb.org/proteinsummary/P02724/annotated"
                },
                {
                    "id": "4091823",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/4091823"
                },
                {
                    "id": "3514617",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/3514617"
                },
                {
                    "id": "6190803",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/6190803"
                },
                {
                    "id": "6619126",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/6619126"
                },
                {
                    "id": "8384526",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/8384526"
                },
                {
                    "id": "7430095",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/7430095"
                }
            ]
        },
        {
            "glytoucan_ac": "G16370GQ",
            "type": "O-linked",
            "subtype": "",
            "site_category": "reported_with_glycan",
            "site_seq": "T",
            "relation": "attached",
            "comment": "GlycoSuiteDB  curation notes. Reported structure can be attached to the following: S-21, T-22, T-23, T-29, S-30, T-31, S-32, T-36, S-38, S-41, T-44, N-45, T-52, T-56, S-63, S-66, T-69",
            "start_aa": "Thr",
            "end_aa": "Thr",
            "residue": "Thr",
            "evidence": [
                {
                    "id": "P02724",
                    "database": "UniCarbKB",
                    "url": "http://unicarbkb.org/proteinsummary/P02724/annotated"
                },
                {
                    "id": "8384526",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/8384526"
                },
                {
                    "id": "7430095",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/7430095"
                },
                {
                    "id": "6619126",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/6619126"
                },
                {
                    "id": "6190803",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/6190803"
                },
                {
                    "id": "3514617",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/3514617"
                },
                {
                    "id": "4091823",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/4091823"
                }
            ]
        },
        {
            "glytoucan_ac": "G33350UC",
            "type": "O-linked",
            "subtype": "",
            "site_category": "reported_with_glycan",
            "site_seq": "T",
            "relation": "attached",
            "comment": "GlycoSuiteDB  curation notes. Reported structure can be attached to the following: S-21, T-22, T-23, T-29, S-30, T-31, S-32, T-36, S-38, S-41, T-44, N-45, T-52, T-56, S-63, S-66, T-69",
            "start_aa": "Thr",
            "end_aa": "Thr",
            "residue": "Thr",
            "evidence": [
                {
                    "id": "P02724",
                    "database": "UniCarbKB",
                    "url": "http://unicarbkb.org/proteinsummary/P02724/annotated"
                },
                {
                    "id": "6619126",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/6619126"
                },
                {
                    "id": "6190803",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/6190803"
                },
                {
                    "id": "3514617",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/3514617"
                },
                {
                    "id": "4091823",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/4091823"
                },
                {
                    "id": "8384526",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/8384526"
                },
                {
                    "id": "7430095",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/7430095"
                }
            ]
        },
        {
            "glytoucan_ac": "G42797SX",
            "type": "O-linked",
            "subtype": "",
            "site_category": "reported_with_glycan",
            "site_seq": "T",
            "relation": "attached",
            "comment": "GlycoSuiteDB  curation notes. Reported structure can be attached to the following: S-21, T-22, T-23, T-29, S-30, T-31, S-32, T-36, S-38, S-41, T-44, N-45, T-52, T-56, S-63, S-66, T-69",
            "start_aa": "Thr",
            "end_aa": "Thr",
            "residue": "Thr",
            "evidence": [
                {
                    "id": "P02724",
                    "database": "UniCarbKB",
                    "url": "http://unicarbkb.org/proteinsummary/P02724/annotated"
                },
                {
                    "id": "7430095",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/7430095"
                },
                {
                    "id": "8384526",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/8384526"
                },
                {
                    "id": "6190803",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/6190803"
                },
                {
                    "id": "4091823",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/4091823"
                },
                {
                    "id": "3514617",
                    "database": "PubMed",
                    "url": "https://glygen.org/publication/PubMed/3514617"
                },
