=== glygener/glygen-backend-api/specs/protein/alignment/response.schema.json
{
    "$schema": "http://json-schema.org/schema#", 
    "required": [], 
    "type": "object", 
    "properties": {
        "similar position": {
            "type": "integer", 
            "description": "", 
            "title": ""
        }, 
        "uniprot_canonical_ac": {
            "type": "string", 
            "description": "", 
            "title": ""
        }, 
        "algorithm": {
            "description": "", 
            "required": [], 
            "type": "object", 
            "properties": {
                "url": {
                    "type": "string", 
                    "description": "", 
                    "title": ""
                }, 
                "parameter": {
                    "type": "string", 
                    "description": "", 
                    "title": ""
                }, 
                "name": {
                    "type": "string", 
                    "description": "", 
                    "title": ""
                }
            }, 
            "title": ""
        }, 
        "protein name": {
            "type": "string", 
            "description": "", 
            "title": ""
        }, 
        "identical position": {
            "type": "integer", 
            "description": "", 
            "title": ""
        }, 
        "identity": {
            "type": "string", 
            "description": "", 
            "title": ""
        }, 
        "sequences": {
            "items": {
                "required": [], 
                "type": "object", 
                "properties": {
                    "protein name": {
                        "type": "string", 
                        "description": "", 
                        "title": ""
                    }, 
                    "uniprot_ac": {
                        "type": "string", 
                        "description": "", 
                        "title": ""
                    }, 
                    "sequence": {
                        "type": "string", 
                        "description": "", 
                        "title": ""
                    }
                }
            }, 
            "type": "array", 
            "description": "", 
            "title": ""
        }, 
        "date": {
            "type": "string", 
            "description": "", 
            "title": ""
        }, 
        "alignment": {
            "type": "string", 
            "description": "", 
            "title": ""
        }
    }
}

=== glygener/glygen-backend-api/specs/protein/alignment/response.example.json
{
   "algorithm":{
      "name":"xyz",
      "url":"xyz",
      "parameter":"The default transition matrix is Gonnet, gap opening penalty is 6 bits, gap extension is 1 bit. Clustal-Omega uses the HHalign algorithm and its default settings as its core alignment engine. The algorithm is described in Söding, J. (2005) 'Protein homology detection by HMM–HMM comparison'. Bioinformatics 21, 951-960"
   },
   "date":"xyz",
   "uniprot_canonical_ac":"P14210-1",
   "protein name":"Hepatocyte growth factor",
   "sequences":[
      {
         "uniprot_ac":"P14210-2",
         "protein name":"Hgf_Human",
         "sequence":"MWVTKLLPALLLQHVLLHLLLLPIAIPYAEGQRKRRNTIHEFKKSAKTTLIKIDPALKIKTKKVNTADQCANRCTRNKGLPFTCKAFVFDKARKQCLWFPFNSMSSGVKKEFGHEFDLYENKDYIRNCIIGKGRSYKGTVSITKSGIKCQPWSSMIPHEHSFLPSSYRGKDLQENYCRNPRGEEGGPWCFTSNPEVRYEVCDIPQCSEVECMTCNGESYRGLMDHTESGKICQRWDHQTPHRHKFLPERYPDKGFDDNYCRNPDGQPRPWCYTLDPHTRWEYCAIKTCET"
      },
      {
         "uniprot_ac":"C9JDP4",
         "protein name":"C9JDP4_Human",
         "sequence":"MWVTKLLPALLLQHVLLHLLLLPIAIPYAEGQRKRRNTIHEFKKSAKTTLIKIDPALKIKTKKVNTADQCANRCTRNKGLPFTCKAFVFDKARKQCLWFPFNSMSSGVKKEFGHEFDLYENKDYIRNCIIGKGRSYKGTVS-----------------------------------------------------------------------------------------------------------------------------------------------------"  }
   ],
   "alignment":"***********************************************************************************************************************************************",
 
   "identical position" :141,
   "identity" :"48.621%",
   "similar position" :0
}
