=== glygener/glygen-backend-api/specs/auth/contactlist/response.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "fname": {
                "type": "string"
            },
            "lname": {
                "type": "string"
            },
            "email": {
                "type": "string"
            },
            "subject": {
                "type": "string"
            },
            "message": {
                "type": "string"
            },
            "page": {
                "type": "string"
            },
            "agent": {
                "type": "string"
            },
            "comment": {
                "type": "string"
            },
            "creation_time": {
                "type": "string"
            },
            "update_time": {
                "type": "string"
            },
            "status": {
                "type": "string"
            },
            "visibility": {
                "type": "string"
            },
            "message_status": {
                "type": "string"
            },
            "id": {
                "type": "string"
            }
        },
        "required": [
        ]
    }
}

=== glygener/glygen-backend-api/tests/responses/auth_contactlist.json
[
    {
        "fname": "Robel",
        "lname": "Kahsay",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-16 13:43:17 ",
        "update_time": "2022-11-16 13:43:17 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "success",
        "id": "63752f45ea77620515fba8b9"
    },
    {
        "fname": "Robel",
        "lname": "Kahsay",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-16 13:43:02 ",
        "update_time": "2022-11-16 13:43:02 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "success",
        "id": "63752f36ea77620515fba87c"
    },
    {
        "fname": "Robel",
        "lname": "Kahsay",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-16 13:37:27 ",
        "update_time": "2022-11-16 13:37:27 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "63752de762278a29a5650871"
    },
    {
        "fname": "Robel",
        "lname": "Kahsay",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-16 13:30:05 ",
        "update_time": "2022-11-16 13:30:05 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "63752c2d91560e9ed0e8f503"
    },
    {
        "fname": "Robel",
        "lname": "Kahsay",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-16 13:26:07 ",
        "update_time": "2022-11-16 13:26:07 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "63752b3feb51edef5d10f595"
    },
    {
        "fname": "Robel",
        "lname": "Kahsay",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-16 13:25:22 ",
        "update_time": "2022-11-16 13:25:22 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "63752b12eb51edef5d10f572"
    },
    {
        "fname": "Robel",
        "lname": "Kahsay",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-16 13:24:49 ",
        "update_time": "2022-11-16 13:24:49 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "63752af1eb51edef5d10f516"
    },
    {
        "fname": "Robel",
        "lname": "Kahsay",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-16 13:23:57 ",
        "update_time": "2022-11-16 13:23:57 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "63752abdeb51edef5d10f4ba"
    },
    {
        "fname": "Robel",
        "lname": "Kahsay",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-16 13:23:37 ",
        "update_time": "2022-11-16 13:23:37 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "63752aa9eb51edef5d10f45e"
    },
    {
        "fname": "Robel",
        "lname": "Kahsay",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-16 13:20:26 ",
        "update_time": "2022-11-16 13:20:26 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "637529eaeb51edef5d10f3ee"
    },
    {
        "fname": "Robel",
        "lname": "Kahsay",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-16 13:11:01 ",
        "update_time": "2022-11-16 13:11:01 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "637527b5eb51edef5d10f392"
    },
    {
        "fname": "Robel",
        "lname": "Kahsay",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-16 13:01:25 ",
        "update_time": "2022-11-16 13:01:25 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "63752575eb51edef5d10f333"
    },
    {
        "fname": "dfafa",
        "lname": "dfafa",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-16 12:29:21 ",
        "update_time": "2022-11-16 12:29:21 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "63751df1eb51edef5d10f2d6"
    },
    {
        "fname": "dfafa",
        "lname": "dfafa",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-15 16:52:32 ",
        "update_time": "2022-11-15 16:52:32 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "63740a20eb51edef5d10f1e6"
    },
    {
        "fname": "dfafa",
        "lname": "dfafa",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-15 16:50:07 ",
        "update_time": "2022-11-15 16:50:07 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "6374098feb51edef5d10f17a"
    },
    {
        "fname": "dfafa",
        "lname": "dfafa",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-15 16:47:07 ",
        "update_time": "2022-11-15 16:47:07 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "637408dbeb51edef5d10f104"
    },
    {
        "fname": "dfafa",
        "lname": "dfafa",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-15 16:45:28 ",
        "update_time": "2022-11-15 16:45:28 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "63740878eb51edef5d10f098"
    },
    {
        "fname": "dfafa",
        "lname": "dfafa",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-15 16:44:30 ",
        "update_time": "2022-11-15 16:44:30 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "6374083eeb51edef5d10f02c"
    },
    {
        "fname": "dfafa",
        "lname": "dfafa",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-15 16:40:59 ",
        "update_time": "2022-11-15 16:40:59 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "6374076beb51edef5d10efc0"
    },
    {
        "fname": "dfafa",
        "lname": "dfafa",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-15 16:40:39 ",
        "update_time": "2022-11-15 16:40:39 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "63740757eb51edef5d10ef54"
    },
    {
        "fname": "dfafa",
        "lname": "dfafa",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-15 16:24:12 ",
        "update_time": "2022-11-15 16:24:12 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "6374037ceb51edef5d10eeeb"
    },
    {
        "fname": "dfafa",
        "lname": "dfafa",
        "email": "rykahsay@gwu.edu",
        "subject": "dfafa",
        "message": "dfaa",
        "page": "",
        "agent": "",
        "comment": "",
        "creation_time": "2022-11-15 16:23:03 ",
        "update_time": "2022-11-15 16:23:03 ",
        "status": "new",
        "visibility": "visible",
        "message_status": "failed",
        "id": "63740337eb51edef5d10ee82"
    },
    {
        "fname": "dfafa",
