=== glygener/glygen-backend-api/specs/motif/detail/response.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "mass": {
            "type": "number"
        },
        "iupac": {
            "type": "string"
        },
        "wurcs": {
            "type": "string"
        },
        "glycoct": {
            "type": "string"
        },
        "crossref": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "database": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "database",
                    "id",
                    "url"
                ]
            }
        },
        "inchi": {
            "type": "string"
        },
        "glycam": {
            "type": "string"
        },
        "smiles_isomeric": {
            "type": "string"
        },
        "publication": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string"
                    },
                    "journal": {
                        "type": "string"
                    },
                    "date": {
                        "type": "string"
                    },
                    "authors": {
                        "type": "string"
                    },
                    "evidence": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "database": {
                                    "type": "string"
                                },
                                "id": {
                                    "type": "string"
                                },
                                "url": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "database",
                                "id",
                                "url"
                            ]
                        }
                    },
                    "reference": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "id": {
                                    "type": "string"
                                },
                                "url": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "id",
                                "type",
                                "url"
                            ]
                        }
                    }
                },
                "required": [
                    "authors",
                    "date",
                    "evidence",
                    "journal",
                    "reference",
                    "title"
                ]
            }
        },
        "synonym": {
            "type": "array"
        },
        "keywords": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "label": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "label",
                    "url"
                ]
            }
        },
        "reducing_end": {
            "type": "string"
        },
        "aglycon": {
            "type": "string"
        },
        "alignment_method": {
            "type": "string"
        },
        "dictionary": {
            "type": "object",
            "properties": {
                "term": {
                    "type": "string"
                },
                "term_in_sentence": {
                    "type": "string"
                },
                "publication": {
                    "type": "string"
                },
                "definition": {
                    "type": "string"
                },
                "term_xref": {
                    "type": "string"
                },
                "best_match": {
                    "type": "string"
                },
                "synonymns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "function": {
                    "type": "string"
                },
                "disease_associations": {
                    "type": "string"
                },
                "wikipedia": {
                    "type": "string"
                },
                "essentials_of_glycobiology": {
                    "type": "string"
                },
                "evidence": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            },
                            "database": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "database",
                            "id",
                            "url"
                        ]
                    }
                }
            },
            "required": [
                "definition",
                "disease_associations",
                "essentials_of_glycobiology",
                "evidence",
                "function",
                "publication",
                "synonymns",
                "term",
                "term_in_sentence",
                "term_xref",
                "wikipedia"
            ]
        },
        "motif": {
            "type": "object",
            "properties": {
                "glytoucan_ac": {
                    "type": "string"
                },
                "accession": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "glytoucan_url": {
                    "type": "string"
                }
            },
            "required": [
                "accession",
                "glytoucan_ac",
                "glytoucan_url",
                "url"
            ]
        },
        "history": {
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "results": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "glytoucan_ac": {
                        "type": "string"
                    },
                    "mass": {
                        "type": "number"
                    },
                    "number_monosaccharides": {
                        "type": "integer"
                    },
                    "number_proteins": {
                        "type": "integer"
                    },
                    "number_enzymes": {
                        "type": "integer"
                    },
                    "iupac": {
                        "type": "string"
                    },
                    "glycoct": {
                        "type": "string"
                    }
                },
                "required": [
                    "glycoct",
                    "glytoucan_ac",
                    "iupac",
                    "mass",
                    "number_enzymes",
                    "number_monosaccharides",
                    "number_proteins"
                ]
            }
        },
        "pagination": {
            "type": "object",
            "properties": {
                "offset": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "total_length": {
                    "type": "integer"
                },
                "sort": {
                    "type": "string"
                },
                "order": {
                    "type": "string"
                }
            },
            "required": [
                "limit",
                "offset",
                "order",
                "sort",
                "total_length"
            ]
        },
        "query": {
            "type": "object",
            "properties": {
                "motif_ac": {
                    "type": "string"
                },
                "offset": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "sort": {
                    "type": "string"
                },
                "order": {
                    "type": "string"
                }
            },
            "required": [
                "limit",
                "motif_ac",
                "offset",
                "order",
                "sort"
            ]
        }
    },
    "required": [
        "aglycon",
        "alignment_method",
        "crossref",
        "dictionary",
        "glycam",
        "glycoct",
        "history",
        "inchi",
        "iupac",
        "keywords",
        "mass",
        "motif",
        "name",
        "pagination",
        "publication",
        "query",
        "reducing_end",
        "results",
        "smiles_isomeric",
        "synonym",
        "wurcs"
    ]
}

=== glygener/glygen-backend-api/tests/responses/motif_detail.json
{
    "mass": 1871.63,
    "iupac": "alpha-D-Neup5Ac-(2->8)-alpha-D-Neup5Ac-(2->3)[alpha-D-Neup5Ac-(2->8)-alpha-D-Neup5Ac-(2->3)-beta-D-Galp-(1->3)-beta-D-GalpNAc-(1->4)]-beta-D-Galp-(1->4)-beta-D-Glcp-(1->",
    "wurcs": "WURCS=2.0/4,8,7/[a2122h-1b_1-5][a2112h-1b_1-5][Aad21122h-2a_2-6_5*NCC/3=O][a2112h-1b_1-5_2*NCC/3=O]/1-2-3-3-4-2-3-3/a4-b1_b3-c2_b4-e1_c8-d2_e3-f1_f3-g2_g8-h2",
    "glycoct": "RES 1b:b-dglc-HEX-1:5 2b:b-dgal-HEX-1:5 3b:a-dgro-dgal-NON-2:6|1:a|2:keto|3:d 4s:n-acetyl 5b:a-dgro-dgal-NON-2:6|1:a|2:keto|3:d 6s:n-acetyl 7b:b-dgal-HEX-1:5 8s:n-acetyl 9b:b-dgal-HEX-1:5 10b:a-dgro-dgal-NON-2:6|1:a|2:keto|3:d 11s:n-acetyl 12b:a-dgro-dgal-NON-2:6|1:a|2:keto|3:d 13s:n-acetyl LIN 1:1o(4+1)2d 2:2o(3+2)3d 3:3d(5+1)4n 4:3o(8+2)5d 5:5d(5+1)6n 6:2o(4+1)7d 7:7d(2+1)8n 8:7o(3+1)9d 9:9o(3+2)10d 10:10d(5+1)11n 11:10o(8+2)12d 12:12d(5+1)13n",
    "crossref": [
        {
            "id": "G18625KA",
            "database": "GlyTouCan",
            "url": "https://glytoucan.org/Structures/Glycans/G18625KA"
        }
    ],
    "inchi": "InChI=1S/C70H113N5O53/c1-18(84)71-35-23(89)6-67(63(106)107,123-53(35)40(95)27(93)10-76)121-31(14-80)44(99)55-37(73-20(3)86)25(91)8-69(125-55,65(110)111)127-57-43(98)30(13-79)116-61(48(57)103)120-52-39(75-22(5)88)60(115-29(12-78)42(52)97)119-51-34(17-83)117-62(118-50-33(16-82)114-59(105)47(102)46(50)101)49(104)58(51)128-70(66(112)113)9-26(92)38(74-21(4)87)56(126-70)45(100)32(15-81)122-68(64(108)109)7-24(90)36(72-19(2)85)54(124-68)41(96)28(94)11-77/h23-62,76-83,89-105H,6-17H2,1-5H3,(H,71,84)(H,72,85)(H,73,86)(H,74,87)(H,75,88)(H,106,107)(H,108,109)(H,110,111)(H,112,113)/t23-,24-,25-,26-,27+,28+,29+,30+,31+,32+,33+,34+,35+,36+,37+,38+,39+,40+,41+,42-,43-,44+,45+,46+,47+,48+,49+,50+,51-,52+,53+,54+,55+,56+,57-,58+,59+,60-,61-,62-,67+,68+,69-,70-/m0/s1",
    "glycam": "DNeup5Aca2-8DNeup5Aca2-3DGalpb1-3DGalpNAcb1-4[DNeup5Aca2-8DNeup5Aca2-3]DGalpb1-4DGlcpb1-OH",
    "smiles_isomeric": "CC(=O)N[C@@H]1[C@H](C[C@@](O[C@H]1[C@@H]([C@@H](CO)O[C@@]2(C[C@@H]([C@H]([C@@H](O2)[C@@H]([C@@H](CO)O)O)NC(=O)C)O)C(=O)O)O)(C(=O)O)O[C@H]3[C@H]([C@H](O[C@H]([C@@H]3O)O[C@@H]4[C@H]([C@@H](O[C@@H]([C@@H]4O)CO)O[C@H]5[C@H](O[C@H]([C@@H]([C@H]5O[C@@]6(C[C@@H]([C@H]([C@@H](O6)[C@@H]([C@@H](CO)O[C@@]7(C[C@@H]([C@H]([C@@H](O7)[C@@H]([C@@H](CO)O)O)NC(=O)C)O)C(=O)O)O)NC(=O)C)O)C(=O)O)O)O[C@@H]8[C@H](O[C@H]([C@@H]([C@H]8O)O)O)CO)CO)NC(=O)C)CO)O)O",
    "publication": [
        {
            "title": "Tetrasialoganglioside GO1b reactive monoclonal antibodies: their characterization and application for quantification of GQ1b in some cell lines of neuronal and adrenal origin(s).",
            "journal": "Journal of neurochemistry",
            "date": "1990",
            "authors": "Yamamoto H, Tsuji S, Nagai Y",
            "evidence": [
                {
                    "database": "Glycan Motif",
                    "id": "GGM.000115",
                    "url": "https://glycomotif.glyomics.org/glycomotif/GGM.000115"
                }
            ],
            "reference": [
                {
                    "type": [
                        "PubMed"
                    ],
                    "id": "2299350",
                    "url": "https://glygen.org/publication/PubMed/2299350"
                }
            ]
        },
        {
            "title": "Fine specificity of anti-GQ1b IgG and clinical features.",
            "journal": "Journal of the neurological sciences",
            "date": "2001",
            "authors": "Susuki K, Yuki N, Hirata K",
            "evidence": [
                {
                    "database": "Glycan Motif",
                    "id": "GGM.000115",
                    "url": "https://glycomotif.glyomics.org/glycomotif/GGM.000115"
                }
            ],
            "reference": [
                {
                    "type": [
                        "PubMed"
                    ],
                    "id": "11266684",
                    "url": "https://glygen.org/publication/PubMed/11266684"
                }
            ]
        },
        {
            "title": "The repertoire of glycan determinants in the human glycome.",
            "journal": "Molecular bioSystems",
            "date": "2009",
            "authors": "Cummings RD",
            "evidence": [
                {
                    "database": "Glycan Motif",
                    "id": "GGM.000115",
                    "url": "https://glycomotif.glyomics.org/glycomotif/GGM.000115"
                }
            ],
            "reference": [
                {
                    "type": [
                        "PubMed"
                    ],
                    "id": "19756298",
                    "url": "https://glygen.org/publication/PubMed/19756298"
                }
            ]
        }
    ],
    "synonym": [],
    "keywords": [
        {
            "label": "Glycolipid",
            "url": "https://glycomotif.glyomics.org/glycomotif/Glycolipid"
        },
        {
            "label": "Tetrasialylated ganglioside",
            "url": "https://glycomotif.glyomics.org/glycomotif/Tetrasialylated_ganglioside"
        }
    ],
    "reducing_end": "true",
    "aglycon": "Cer",
    "alignment_method": "Whole-Glycan",
    "dictionary": {
        "term": "GQ1b",
        "term_in_sentence": "Bilateral infusion of GQ1b into the hippocampus ameliorates cognitive deficits in the triple-transgenic AD mouse model (3xTg-AD).[PMID:31186474]",
        "publication": "30798387|31186474|26704905|23677659|26984947|24184316|23804237|9819299|18514410|22189683|24859332",
        "definition": "An amino oligosaccharide that is a branched octasaccharide derivative consisting of four sialyl residues, two galactose residues, one N-acetylglucosamine and a glucose residue at the reducing end.[CHEBI:59212]",
        "term_xref": "GlycoMotif:GGM.000115|GlycoEpitope:EP0069|CID:45266843|KEGG:G00117|CHEBI:59212",
        "best_match": "GlycoMotif:GGM.000115|GTC:G18625KA|GlycoEpitope:EP0069|CID:45266843|KEGG:G00117|CHEBI:59212",
        "synonymns": [
            ""
        ],
        "function": "",
        "disease_associations": "",
        "wikipedia": "",
        "essentials_of_glycobiology": "NBK453016",
        "evidence": [
            {
                "id": "GD000096",
                "url": "https://wiki.glygen.org/index.php/Glycan_structure_dictionary#GD000096",
                "database": "Glycan Dictionary"
            }
        ]
    },
    "motif": {
        "glytoucan_ac": "G18625KA",
        "accession": "GGM.000115",
        "url": "https://glycomotif.glyomics.org/glycomotif/GGM.000115",
        "glytoucan_url": "https://glytoucan.org/Structures/Glycans/G18625KA"
    },
    "history": [],
    "name": "GQ1b",
    "results": [
        {
            "glytoucan_ac": "G18625KA",
            "mass": 1871.63,
            "number_monosaccharides": 8,
            "number_proteins": 0,
            "number_enzymes": 0,
            "iupac": "alpha-D-Neup5Ac-(2->8)-alpha-D-Neup5Ac-(2->3)[alpha-D-Neup5Ac-(2->8)-alpha-D-Neup5Ac-(2->3)-beta-D-Galp-(1->3)-beta-D-GalpNAc-(1->4)]-beta-D-Galp-(1->4)-beta-D-Glcp-(1->",
            "glycoct": "RES 1b:b-dglc-HEX-1:5 2b:b-dgal-HEX-1:5 3b:a-dgro-dgal-NON-2:6|1:a|2:keto|3:d 4s:n-acetyl 5b:a-dgro-dgal-NON-2:6|1:a|2:keto|3:d 6s:n-acetyl 7b:b-dgal-HEX-1:5 8s:n-acetyl 9b:b-dgal-HEX-1:5 10b:a-dgro-dgal-NON-2:6|1:a|2:keto|3:d 11s:n-acetyl 12b:a-dgro-dgal-NON-2:6|1:a|2:keto|3:d 13s:n-acetyl LIN 1:1o(4+1)2d 2:2o(3+2)3d 3:3d(5+1)4n 4:3o(8+2)5d 5:5d(5+1)6n 6:2o(4+1)7d 7:7d(2+1)8n 8:7o(3+1)9d 9:9o(3+2)10d 10:10d(5+1)11n 11:10o(8+2)12d 12:12d(5+1)13n"
        }
    ],
    "pagination": {
        "offset": 1,
        "limit": 20,
        "total_length": 1,
        "sort": "glytoucan_ac",
        "order": "asc"
    },
    "query": {
        "motif_ac": "GGM.000115",
        "offset": 1,
        "limit": 20,
        "sort": "glytoucan_ac",
        "order": "asc"
    }
}
