=== glygener/glygen-backend-api/specs/auth/login/response.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "access_csrf": {
            "type": "string"
        },
        "access_token": {
            "type": "string"
        },
        "refresh_csrf": {
            "type": "string"
        },
        "status": {
            "type": "integer"
        },
        "username": {
            "type": "string"
        }
    },
    "required": [
        "access_csrf",
        "access_token",
        "refresh_csrf",
        "status",
        "username"
    ]
}

=== glygener/glygen-backend-api/tests/responses/auth_login.json
{
    "access_csrf": "fda74d42-0d03-466e-b617-117fda814141",
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2Njg3MDkyNzAsIm5iZiI6MTY2ODcwOTI3MCwianRpIjoiYmZhYzA0NDQtMDAyZC00Yjc1LWJjMTAtZDlmMTUyOGFiZGVlIiwiZXhwIjoxNjY4Nzk1NjcwLCJpZGVudGl0eSI6InJ5a2Foc2F5QGd3dS5lZHUiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MiLCJjc3JmIjoiZmRhNzRkNDItMGQwMy00NjZlLWI2MTctMTE3ZmRhODE0MTQxIn0.DZHkLr_ZOV9X0uCIMwaXvQzzhVgPZElTOinf-Pxy_Ik",
    "refresh_csrf": "7c47e580-2489-4601-8f69-6a263bcc9f49",
    "status": 1,
    "username": "rykahsay@gwu.edu"
}
