=== glygener/glygen-backend-api/specs/protein/list/response.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "cache_info": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "object",
                    "properties": {
                        "uniprot_canonical_ac": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "uniprot_canonical_ac"
                    ]
                },
                "ts": {
                    "type": "string"
                },
                "record_type": {
                    "type": "string"
                },
                "search_type": {
                    "type": "string"
                }
            },
            "required": [
                "query",
                "record_type",
                "search_type",
                "ts"
            ]
        },
        "filters": {
            "type": "object",
            "properties": {
                "applied": {
                    "type": "array"
                },
                "available": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "label": {
                                "type": "string"
                            },
                            "order": {
                                "type": "integer"
                            },
                            "tooltip": {
                                "type": "string"
                            },
                            "options": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "label": {
                                            "type": "string"
                                        },
                                        "count": {
                                            "type": "integer"
                                        },
                                        "order": {
                                            "type": "integer"
                                        }
                                    },
                                    "required": [
                                        "count",
                                        "id",
                                        "label",
                                        "order"
                                    ]
                                }
                            }
                        },
                        "required": [
                            "id",
                            "label",
                            "options",
                            "order",
                            "tooltip"
                        ]
                    }
                }
            },
            "required": [
                "applied",
                "available"
            ]
        },
        "results": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "uniprot_canonical_ac": {
                        "type": "string"
                    },
                    "mass": {
                        "type": "number"
                    },
                    "protein_name": {
                        "type": "string"
                    },
                    "gene_name": {
                        "type": "string"
                    },
                    "organism": {
                        "type": "string"
                    },
                    "refseq_name": {
                        "type": "string"
                    },
                    "refseq_ac": {
                        "type": "string"
                    },
                    "gene_names_uniprotkb": {
                        "type": "string"
                    },
                    "gene_names_refseq": {
                        "type": "string"
                    },
                    "protein_names_uniprotkb": {
                        "type": "string"
                    },
                    "protein_names_refseq": {
                        "type": "string"
                    },
                    "tax_id": {
                        "type": "integer"
                    },
                    "disease": {
                        "type": "string"
                    },
                    "pathway": {
                        "type": "string"
                    },
                    "publication_count": {
                        "type": "integer"
                    },
                    "function": {
                        "type": "string"
                    },
                    "predicted_glycosites": {
                        "type": "integer"
                    },
                    "predicted_n_glycosites": {
                        "type": "integer"
                    },
                    "predicted_o_glycosites": {
                        "type": "integer"
                    },
                    "reported_n_glycosites": {
                        "type": "integer"
                    },
                    "reported_o_glycosites": {
                        "type": "integer"
                    },
                    "reported_n_glycosites_with_glycan": {
                        "type": "integer"
                    },
                    "reported_o_glycosites_with_glycan": {
                        "type": "integer"
                    },
                    "total_reported_n_glycosites": {
                        "type": "integer"
                    },
                    "total_reported_o_glycosites": {
                        "type": "integer"
                    },
                    "total_n_glycosites": {
                        "type": "integer"
                    },
                    "total_o_glycosites": {
                        "type": "integer"
                    },
                    "reported_fully_resolved_glycans": {
                        "type": "integer"
                    },
                    "reported_phosphosites": {
                        "type": "integer"
                    },
                    "reported_mutagensis": {
                        "type": "integer"
                    },
                    "reported_glycation": {
                        "type": "integer"
                    },
                    "reported_snv": {
                        "type": "integer"
                    },
                    "reported_interactions": {
                        "type": "integer"
                    },
                    "missing_score": {
                        "type": "integer"
                    },
                    "record_type": {
                        "type": "string"
                    },
                    "hit_score": {
                        "type": "number"
                    },
                    "score_info": {
                        "type": "object",
                        "properties": {
                            "contributions": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "c": {
                                            "type": "string"
                                        },
                                        "w": {
                                            "type": "number"
                                        },
                                        "f": {
                                            "type": "number"
                                        }
                                    },
                                    "required": [
                                        "c",
                                        "f",
                                        "w"
                                    ]
                                }
                            },
                            "formula": {
                                "type": "string"
                            },
                            "variables": {
                                "type": "object",
                                "properties": {
                                    "c": {
                                        "type": "string"
                                    },
                                    "w": {
                                        "type": "string"
                                    },
                                    "f": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "c",
                                    "f",
                                    "w"
                                ]
                            }
                        },
                        "required": [
                            "contributions",
                            "formula",
                            "variables"
                        ]
                    }
                },
                "required": [
                    "disease",
                    "function",
                    "gene_name",
                    "gene_names_refseq",
                    "gene_names_uniprotkb",
                    "hit_score",
                    "mass",
                    "missing_score",
                    "organism",
                    "pathway",
                    "predicted_glycosites",
                    "predicted_n_glycosites",
                    "predicted_o_glycosites",
                    "protein_name",
                    "protein_names_refseq",
                    "protein_names_uniprotkb",
                    "publication_count",
                    "record_type",
                    "refseq_ac",
                    "refseq_name",
                    "reported_fully_resolved_glycans",
                    "reported_glycation",
                    "reported_interactions",
                    "reported_mutagensis",
                    "reported_n_glycosites",
                    "reported_n_glycosites_with_glycan",
                    "reported_o_glycosites",
                    "reported_o_glycosites_with_glycan",
                    "reported_phosphosites",
                    "reported_snv",
                    "score_info",
                    "tax_id",
                    "total_n_glycosites",
                    "total_o_glycosites",
                    "total_reported_n_glycosites",
                    "total_reported_o_glycosites",
                    "uniprot_canonical_ac"
                ]
            }
        },
        "pagination": {
            "type": "object",
            "properties": {
                "offset": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "total_length": {
                    "type": "integer"
                },
                "sort": {
                    "type": "string"
                },
                "order": {
                    "type": "string"
                }
            },
            "required": [
                "limit",
                "offset",
                "order",
                "sort",
                "total_length"
            ]
        }
    },
    "required": [
        "cache_info",
        "filters",
        "pagination",
        "results"
    ]
}

=== glygener/glygen-backend-api/tests/responses/protein_list.json
{
    "cache_info": {
        "query": {
            "uniprot_canonical_ac": "P14210"
        },
        "ts": "2022-11-16 13:43:16 EST-0500",
        "record_type": "protein",
        "search_type": "search"
    },
    "filters": {
        "applied": [],
        "available": [
            {
                "id": "by_mass",
                "label": "By Mass",
                "order": 4,
                "tooltip": "",
                "options": [
                    {
                        "id": "0k_100k",
                        "label": "< 100K",
                        "count": 1,
                        "order": 1
                    }
                ]
            },
            {
                "id": "by_organism",
                "label": "By Organism",
                "order": 2,
                "tooltip": "",
                "options": [
                    {
                        "id": "Homo sapiens",
                        "label": "Human",
                        "count": 1,
                        "order": 1
                    }
                ]
            },
            {
                "id": "by_ptm",
                "label": "By PTM",
                "order": 1,
                "tooltip": "",
                "options": [
                    {
                        "id": "N-Glycosylation reported",
                        "label": "N-Glycosylation reported",
                        "count": 1,
                        "order": 1
                    },
                    {
                        "id": "O-Glycosylation reported",
                        "label": "O-Glycosylation reported",
                        "count": 1,
                        "order": 2
                    }
                ]
            },
            {
                "id": "by_data",
                "label": "By Data",
                "order": 3,
                "tooltip": "",
                "options": [
                    {
                        "id": "Mutagenesis",
                        "label": "Mutagenesis",
                        "count": 1,
                        "order": 1
                    },
                    {
                        "id": "SNV",
                        "label": "SNV",
                        "count": 1,
                        "order": 2
                    },
                    {
                        "id": "Pathway",
                        "label": "Pathway",
                        "count": 1,
                        "order": 3
                    },
                    {
                        "id": "Disease",
                        "label": "Disease",
                        "count": 1,
                        "order": 4
                    },
                    {
                        "id": "Binding",
                        "label": "Binding",
                        "count": 1,
                        "order": 6
                    },
                    {
                        "id": "Publication",
                        "label": "Publication",
                        "count": 1,
                        "order": 7
                    }
                ]
            }
        ]
    },
    "results": [
        {
            "uniprot_canonical_ac": "P14210-1",
            "mass": 83134.0,
            "protein_name": "Hepatocyte growth factor",
            "gene_name": "HGF",
            "organism": "Homo sapiens",
            "refseq_name": "hepatocyte growth factor isoform 1 preproprotein",
            "refseq_ac": "NP_000592",
            "gene_names_uniprotkb": "HGF; HPTA",
            "gene_names_refseq": "DFNB39; F-TCF; HGFB; HPTA; SF; HGF",
            "protein_names_uniprotkb": "Hepatocyte growth factor; Hepatopoietin-A; SF; Scatter factor",
            "protein_names_refseq": "fibroblast-derived tumor cytotoxic factor; lung fibroblast-derived mitogen; hepatopoietin-A; hepatocyte growth factor (hepapoietin A; scatter factor); hepatocyte growth factor isoform 1 preproprotein",
            "tax_id": 9606,
            "disease": "autosomal recessive nonsyndromic deafness 39 (Disease Ontology:DOID:0110497)",
            "pathway": " (hsa:3082); Platelet degranulation (R-HSA-114608); PIP3 activates AKT signaling (R-HSA-1257604); Interleukin-7 signaling (R-HSA-1266695); Constitutive Signaling by Aberrant PI3K in Cancer (R-HSA-2219530); RAF/MAP kinase cascade (R-HSA-5673001); Interleukin-4 and Interleukin-13 signaling (R-HSA-6785807); MET Receptor Activation (R-HSA-6806942); Negative regulation of MET activity (R-HSA-6807004); PI5P, PP2A and IER3 Regulate PI3K/AKT Signaling (R-HSA-6811558); MET activates RAS signaling (R-HSA-8851805); MET activates PI3K/AKT signaling (R-HSA-8851907); MET activates PTPN11 (R-HSA-8865999); MET activates PTK2 signaling (R-HSA-8874081); MET interacts with TNS proteins (R-HSA-8875513); MET activates RAP1 and RAC1 (R-HSA-8875555); MET receptor recycling (R-HSA-8875656); MET activates STAT3 (R-HSA-8875791); Drug-mediated inhibition of MET activation (R-HSA-9734091)",
            "publication_count": 26,
            "function": "14-3-3 Sigma Protein Contributes to Hepatocyte Growth Factor-mediated Cell Proliferation and Invasion via Matrix Metalloproteinase-1 Regulation in Human Gastric Cancer., [RefSeq, PubMed]; Associations of the cerebrospinal fluid hepatocyte growth factor with Alzheimer's disease pathology and cognitive function. Publication Status: Online-Only, [RefSeq, PubMed]; MiR-204 suppresses the progression of acute myeloid leukemia through HGF/c-Met pathway., [RefSeq, PubMed]; Potent mitogen for mature parenchymal hepatocyte cells, seems to be a hepatotrophic factor, and acts as a growth factor for a broad spectrum of tissues and cell types. Activating ligand for the receptor tyrosine kinase MET by binding to it and promoting its dimerization., [UniProtKB, PubMed, PubMed]; This gene encodes a protein that binds to the hepatocyte growth factor receptor to regulate cell growth, cell motility and morphogenesis in numerous cell and tissue types. Alternative splicing results in multiple transcript variants, at least one of which encodes a preproprotein that is proteolytically processed to generate alpha and beta chains, which form the mature heterodimer. This protein is secreted by mesenchymal cells and acts as a multi-functional cytokine on cells of mainly epithelial origin. This protein also plays a role in angiogenesis, tumorogenesis, and tissue regeneration. Although the encoded protein is a member of the peptidase S1 family of serine proteases, it lacks peptidase activity. Mutations in this gene are associated with nonsyndromic hearing loss. [provided by RefSeq, Nov 2015]., [RefSeq]; Three subtypes of lung cancer fibroblasts define distinct therapeutic paradigms., [RefSeq, PubMed]",
            "predicted_glycosites": 0,
            "predicted_n_glycosites": 0,
            "predicted_o_glycosites": 0,
            "reported_n_glycosites": 4,
            "reported_o_glycosites": 1,
            "reported_n_glycosites_with_glycan": 9,
            "reported_o_glycosites_with_glycan": 1,
            "total_reported_n_glycosites": 13,
            "total_reported_o_glycosites": 2,
            "total_n_glycosites": 13,
            "total_o_glycosites": 2,
            "reported_fully_resolved_glycans": 2,
            "reported_phosphosites": 0,
            "reported_mutagensis": 1,
            "reported_glycation": 0,
            "reported_snv": 22,
            "reported_interactions": 1,
            "missing_score": 0,
            "record_type": "protein",
            "hit_score": 85.54,
            "score_info": {
                "contributions": [
                    {
                        "c": "protein_exact_match",
                        "w": 50.0,
                        "f": 1.0
                    },
                    {
                        "c": "protein_top_glycan_definition_score",
                        "w": 1.0,
                        "f": 400.0
                    },
                    {
                        "c": "protein_reported_fully_resolved_glycans",
                        "w": 10.0,
                        "f": 2.0
                    },
                    {
                        "c": "protein_reported_n_glycosites_with_glycan",
                        "w": 5.0,
                        "f": 9.0
                    },
                    {
                        "c": "protein_reported_o_glycosites_with_glycan",
                        "w": 5.0,
                        "f": 1.0
                    },
                    {
                        "c": "protein_reported_n_glycosites",
                        "w": 4.0,
                        "f": 4.0
                    },
                    {
                        "c": "protein_reported_o_glycosites",
                        "w": 4.0,
                        "f": 1.0
                    },
                    {
                        "c": "protein_predicted_glycosites",
                        "w": 0.0,
                        "f": 0.0
                    },
                    {
                        "c": "protein_publication_count",
                        "w": 2.0,
                        "f": 26.0
                    }
                ],
                "formula": "sum(w + 0.01*f)",
                "variables": {
                    "c": "condition name",
                    "w": "condition weight",
                    "f": "condition match frequency"
                }
            }
        }
    ],
    "pagination": {
        "offset": 1,
        "limit": 20,
        "total_length": 1,
        "sort": "hit_score",
        "order": "desc"
    }
}
