=== glygener/glygen-backend-api/specs/event/detail/response.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "start_date": {
            "type": "string"
        },
        "end_date": {
            "type": "string"
        },
        "venue": {
            "type": "string"
        },
        "url": {
            "type": "string"
        },
        "url_name": {
            "type": "string"
        },
        "visibility": {
            "type": "string"
        },
        "createdts": {
            "type": "string"
        },
        "updatedts": {
            "type": "string"
        },
        "id": {
            "type": "string"
        }
    },
    "required": [
        "createdts",
        "description",
        "end_date",
        "id",
        "start_date",
        "title",
        "updatedts",
        "url",
        "url_name",
        "venue",
        "visibility"
    ]
}

=== glygener/glygen-backend-api/tests/responses/event_detail.json
{
    "title": "some title",
    "description": "some description",
    "start_date": "2021-01-20 23:59:59 ",
    "end_date": "2021-01-21 07:00:00 ",
    "venue": "some venue",
    "url": "some url",
    "url_name": "some url name",
    "visibility": "visible",
    "createdts": "2022-11-09 11:56:14 ",
    "updatedts": "2022-11-09 11:56:14 ",
    "id": "636bdbae7b18763522a94293"
}
